version: "3.6"
services:
  # Define a new service
  exemplar:
    build:
      # Build the service from the Dockerfile in ./Exemplars
      context: ./Exemplars
    environment:
      # Listen on 0.0.0.0 to accept connections from any host.
      HOST: "0.0.0.0"
      PORT: "3000"
    ports:
      # Expose internal port 3000 on external port 4000.
      - 4000:3000
  # Defines the account service
  accounts:
    build:
      # Build the account service from the Dockerfile in ./IdentityManagement
      context: ./IdentityManagement
    environment:
      # Listen on 0.0.0.0 to accept connections from any host.
      HOST: "0.0.0.0"
      PORT: "3000"
    ports:
      # Expose internal port 3000 on external port 6000.
      - 6000:3000
